env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: "./tsconfig.eslint.json"
rules:
  {
    import/extensions: "off",
    import/no-unresolved: "off",
    import/named: 0,
    import/prefer-default-export: "off",
    "@typescript-eslint/strict-boolean-expressions": "off",
    "@typescript-eslint/member-delimiter-style":
      [
        "error",
        {
          "multiline": { "delimiter": "semi", "requireLast": true },
          "singleline": { "delimiter": "semi", "requireLast": false },
          "multilineDetection": "brackets",
        },
      ],
    "@typescript-eslint/restrict-template-expressions": "off",
  }