version: "3"

services:
  database:
    image: postgres:latest
    container_name: aya-test-db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_PORT=5432
      - POSTGRES_USER=development
      - POSTGRES_PASSWORD=development
      - POSTGRES_DB=aya-test-db
